# Generated by Django 2.0.1 on 2018-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='users/default_profile_image.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
