# Generated by Django 2.0.1 on 2018-01-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180117_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='activation_key',
            field=models.CharField(default=None, max_length=35),
            preserve_default=False,
        ),
    ]
