# Generated by Django 2.0.1 on 2018-01-19 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180119_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activation_key',
        ),
    ]
