# Generated by Django 2.0.1 on 2018-01-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180119_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activation_key',
        ),
    ]
