# Generated by Django 2.0.1 on 2018-01-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='total_likes',
        ),
    ]
