# Generated by Django 2.0.1 on 2018-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20180120_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
