# Generated by Django 2.0.1 on 2018-01-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_image_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
    ]
