# Generated by Django 2.0.1 on 2018-05-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_image_num_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='num_views',
        ),
    ]
